#ifndef Display_H_
#define Display_H_


// https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf

#define DISPLAY_SET_CONTRAST 0x81 // [0-255]
#define DISPLAY_SHOW_RAM 0xA4
#define DISPLAY_ALL_ON 0xA5
#define DISPLAY_SET_NORMAL 0xA6
#define DISPLAY_SET_INVERSE 0xA7
#define DISPLAY_ON 0xAF
#define DISPLAY_OFF 0xAE

#define DISPLAY_SET_ADDRESS_MODE 0x20 // [DISPLAY_ADDRESS_MODE_*]
#define DISPLAY_ADDRESS_MODE_HORIZONTAL 0x0
#define DISPLAY_ADDRESS_MODE_VERTICAL 0x1
#define DISPLAY_ADDRESS_MODE_PAGE 0x2
#define DISPLAY_ADDRESS_MODE_INVALID 0x3

#define DISPLAY_SET_COLUMN_ADDRESS 0x21 // [0-127][0-127]

#define DISPLAY_SET_PAGE_ADDRESS 0x22 // [0-7][0-7]
#define DISPLAY_SET_PAGE_START_ADDRESS 0xB0 // | [0-7]
#define DISPLAY_SET_START_LINE 0x40 // +0b11111

#define DISPLAY_SET_SEGMENT_REMAP_OFF 0xA0 // column address 0 is mapped to SEG0 (RESET)
#define DISPLAY_SET_SEGMENT_REMAP_ON  0xA1 // column address 127 is mapped to SEG0

#define DISPLAY_SET_MULTIPLEX_RATIO 0xA8 // [0-63]
#define DISPLAY_MULTIPLEX_RESET 0x3F

#define DISPLAY_SET_SCAN_DIRECTION_NORMAL 0xC0
#define DISPLAY_SET_SCAN_DIRECTION_REMAP 0xC8

#define DISPLAY_SET_OFFSET 0xD3 // [0-63]

#define DISPLAY_SET_CHARGE_PUMP 0x8D // [DISPLAY_CHARGE_PUMP_*]
#define DISPLAY_CHARGE_PUMP_OFF 0x10
#define DISPLAY_CHARGE_PUMP_ON 0x14

#define DISPLAY_SET_COM_PINS 0xDA // [DISPLAY_COM_*]
#define DISPLAY_COM_NONE 0x02
#define DISPLAY_COM_ALTERNATIVE 0x12
#define DISPLAY_COM_LEFT_RIGHT_REMAP 0x22

#define DISPLAY_SET_CLOCK_DIVIDE 0xD5 // [0-255]
#define DISPLAY_SET_PRECHARGE_PERIOD 0xD9 // [0-255]

#define DISPLAY_SET_DESELECT_LEVEL 0xDB // Byte (look this up)


#define DISPLAY_SET_LOWER_COLUMN 0x00
#define DISPLAY_SET_HIGHER_COLUMN 0x10

#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64
#define DISPLAY_WRITE_SIZE 8


void InitializeDisplay();


#endif /* DISPLAY_H_ */
